/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.68, 2.533, 1.337]} scale={[2.816, 0.059, 2.816]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['Black marble']} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials['White Painted Wood']} />
        <mesh geometry={nodes.Cube009_3.geometry} material={materials['White Painted Wood']} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
